CREATE TABLE "GCG_4340_BOM_PreProc"(
 "AutoNum" IDENTITY DEFAULT '0',
 "BIRUNID" INTEGER,
 "ITEM_no" CHAR(8),
 "COMPONENT" CHAR(20),
 "REV" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "QTY" NUMERIC(12,4),
 "UM" CHAR(3),
 "SHEAR_SIZE" CHAR(50),
 "MATERIAL" CHAR(30),
 "PROGRAM_NO" CHAR(23),
 "DEPT" CHAR(30),
 UNIQUE ("AutoNum"));